// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoiexdGs6gGCwF0dgCRjOo4urJBb8KoZc',
    appId: '1:992919478764:web:1c74d618b0411e47e020c9',
    messagingSenderId: '992919478764',
    projectId: 'lifeflow-e02db',
    authDomain: 'lifeflow-e02db.firebaseapp.com',
    storageBucket: 'lifeflow-e02db.firebasestorage.app',
    measurementId: 'G-DSMKCJH3K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEgaRudVIFaI7l6Fw34rR4IWqx08QLnAI',
    appId: '1:992919478764:android:79a20a41eadf77d8e020c9',
    messagingSenderId: '992919478764',
    projectId: 'lifeflow-e02db',
    storageBucket: 'lifeflow-e02db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZJRPEkZlz3rHvohOkCCN1fZ8ZFqkgqgQ',
    appId: '1:992919478764:ios:6b6f37e6ad1852f2e020c9',
    messagingSenderId: '992919478764',
    projectId: 'lifeflow-e02db',
    storageBucket: 'lifeflow-e02db.firebasestorage.app',
    iosClientId: '992919478764-09g4913pq46bhtck8tmlifvt0dh5ohq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZJRPEkZlz3rHvohOkCCN1fZ8ZFqkgqgQ',
    appId: '1:992919478764:ios:6b6f37e6ad1852f2e020c9',
    messagingSenderId: '992919478764',
    projectId: 'lifeflow-e02db',
    storageBucket: 'lifeflow-e02db.firebasestorage.app',
    iosClientId: '992919478764-09g4913pq46bhtck8tmlifvt0dh5ohq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoiexdGs6gGCwF0dgCRjOo4urJBb8KoZc',
    appId: '1:992919478764:web:93469a0fc2bf21e6e020c9',
    messagingSenderId: '992919478764',
    projectId: 'lifeflow-e02db',
    authDomain: 'lifeflow-e02db.firebaseapp.com',
    storageBucket: 'lifeflow-e02db.firebasestorage.app',
    measurementId: 'G-51DMQSRGBJ',
  );
}
